# This rule is not used by the project githubissue-operator-assignment-shviro itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to github.itayshviro.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: githubissue-operator-assignment-shviro
    app.kubernetes.io/managed-by: kustomize
  name: githubissue-viewer-role
rules:
- apiGroups:
  - github.itayshviro.dev
  resources:
  - githubissues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.itayshviro.dev
  resources:
  - githubissues/status
  verbs:
  - get
