apiVersion: github.itayshviro.dev/v1alpha1
kind: GithubIssue
metadata:
  name: important-issue-dup
  namespace: default
spec:
  repo: https://github.com/itayShv/githubIssue-operator-assignment-shviro
  title: Important issue
  description: very very